controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login_check:
    path:     /login_check

register_check:
    path:     /register_check

app_react:
    path: /{reactRouting}
    controller: App\Controller\DefaultController::index
    requirements:
        reactRouting: .*

    