controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


api:
    path: /api
    controller: App\Controller\DefaultController::api

login_check:
    path:     /api/login_check
    methods:  [POST]